/**
 * All user-facing copy (zh-CN), kept in one place so it can later be swapped
 * for a real i18n table. Original prose — do not copy text from other projects.
 */

export const STRINGS = {
  welcome: {
    title: '欢迎使用 FISHCODE',
    subtitle: '把 DeepSeek Harness 装进一个安静的桌面应用。',
    steps: [
      {
        title: '连接 DeepSeek',
        body: '需要一个 DeepSeek 平台的 API Key。它只保存在你自己的电脑上，不会上传。',
      },
      {
        title: '按你的习惯配置',
        body: '决定是否开机自启、关闭时是否最小化到托盘、是否显示桌面萌宠。',
      },
      {
        title: '开始工作',
        body: '设置完成后，就可以用 FISHCODE 聊天、写代码、整理文件了。',
      },
    ],
    apiKeyButton: '获取 API Key',
    backButton: '上一步',
    nextButton: '下一步',
    finishButton: '开始使用',
    skipButton: '跳过设置',
    visionLink: '视觉服务（可选）',
    visionHint: '免费开启图片识别能力，可随时在托盘菜单中配置。',
    toggles: {
      autoLaunch: '开机自启',
      minimizeToTray: '关闭窗口时最小化到托盘',
      petEnabled: '显示桌面萌宠',
    },
  },
  notify: {
    completeTitle: 'FISHCODE',
    completeBody: '任务完成了，可以继续下一步。',
    backendFailedTitle: 'FISHCODE 后端异常',
    backendFailedBody: '本地服务没能启动，请查看日志或重启应用。',
    hotkeyFailedTitle: '全局快捷键不可用',
    hotkeyFailedBody: 'Ctrl+Shift+D 已被其他程序占用，可用托盘图标显示窗口。',
    openWithInstalledTitle: '已安装右键菜单',
    openWithInstalledBody: '在文件上右键即可选择「用 FISHCODE 打开」。',
    openWithFailedTitle: '安装右键菜单失败',
    openWithFailedBody: '无法写入系统注册表，请稍后重试。',
  },
  pet: {
    greet: ['你好呀', '我在呢', '有需要就叫我'],
    done: ['搞定啦！', '做完了，喝口水休息一下？'],
    hide: '隐藏萌宠',
    actionMenu: '萌宠动作',
    actions: {
      idle: '待机',
      eat: '庆祝',
      sleep: '睡觉',
      'walk-left': '走路（向左）',
      'walk-right': '走路（向右）',
      working: '工作',
      ciallo: '启动动画',
    },
  },
  loading: {
    title: 'FISHCODE 正在启动',
    starting: '正在启动本地服务…',
    restarting: '本地服务重启中…',
    failed: '本地服务启动失败',
    failedHint: '请稍后重试，或重启应用。',
    retry: '重试',
  },
  tray: {
    show: '显示主窗口',
    togglePet: '显示 / 隐藏桌面萌宠',
    visionSetup: '视觉服务设置',
    openWithInstall: '安装「用 FISHCODE 打开」',
    openWithInstalled: '「用 FISHCODE 打开」已安装',
    openWithMenu: '用 FISHCODE 打开',
    balanceRefresh: '刷新余额',
    balanceConsole: '打开 DeepSeek 控制台',
    balanceLoading: 'DeepSeek 余额：查询中…',
    balanceMissingKey: 'DeepSeek 余额：未配置 API Key',
    balanceError: 'DeepSeek 余额：获取失败',
    checkForUpdates: '检查更新…',
    quit: '退出',
  },
  update: {
    title: '软件更新',
    available: '发现新版本 v{version}（当前 v{current}）',
    availableDetail:
      '是否现在下载？下载完成后会在重启应用时静默安装，不会影响你的本地数据。\n若网络受限，可点「手动下载」用浏览器打开发布页。',
    downloadNow: '下载并安装',
    later: '稍后',
    manualDownload: '手动下载',
    downloading: '更新下载中 {percent}%',
    downloaded: '更新已下载',
    downloadedDetail: '重启应用即可完成安装，请先保存当前工作。',
    installNow: '立即重启安装',
    upToDate: '已是最新版本',
    checkFailed: '检查更新失败，可前往 GitHub Releases 手动下载。',
    close: '关闭',
  },
  menu: {
    file: '文件',
    edit: '编辑',
    view: '视图',
    window: '窗口',
    help: '帮助',
    quit: '退出',
    undo: '撤销',
    redo: '重做',
    cut: '剪切',
    copy: '复制',
    paste: '粘贴',
    delete: '删除',
    selectAll: '全选',
    reload: '重新加载',
    forceReload: '强制重新加载',
    actualSize: '实际大小',
    zoomIn: '放大',
    zoomOut: '缩小',
    fullScreen: '全屏',
    minimize: '最小化',
    maximize: '最大化',
    close: '关闭',
    docs: 'DeepSeek API 文档',
    // api-docs.deepseek.com 国内可直连（docs.deepseek.com 已无法访问，勿改回）。
    docsUrl: 'https://api-docs.deepseek.com/',
    about: '关于 FISHCODE',
    aboutBody: '基于 DeepSeek Harness 的本地桌面应用（非 DeepSeek 官方出品）。\n数据都在本机运行，不会上传。',
  },
  settings: {
    recovered: '配置文件已损坏，已备份并重置为默认值。',
  },
  sessionDelete: {
    notifyTitle: '会话删除',
    confirmTitle: '确认删除会话',
    noTitle: '（无标题）',
    confirmBody: '将永久删除会话「{title}」。此操作不可恢复，确定继续？',
    confirmDelete: '删除',
    cancel: '取消',
    refusedCurrent: '当前打开的会话不能删除。',
    refusedActive: '该会话正在运行中，暂时不能删除。',
    missing: '没有找到该会话，可能已被删除。',
    failed: '删除失败：{detail}',
  },
  visionSetup: {
    title: '视觉服务设置',
    subtitle: '让 FISHCODE 看懂图片：粘贴或拖入截图，模型即可识别其中的内容。',
    statusChecking: '正在读取配置…',
    statusConfigured: '当前：{provider} 已配置',
    statusCustom: '当前：自定义服务已配置',
    statusNone: '当前：未配置',
    providerLabel: '服务商',
    providerZhipu: '智谱 GLM-4V-Flash（免费）',
    providerCustom: '自定义',
    presetNote: '智谱开放平台提供免费的 GLM-4V-Flash 多模态模型，注册即可领取 API Key。',
    getKeyButton: '获取智谱 API Key',
    keyLabel: 'API Key',
    keyPlaceholder: '粘贴你的 API Key',
    keyHelp: '密钥只保存在本机 ~/.dsh/.credentials.yaml，不会上传给 FISHCODE。',
    showKey: '显示',
    customBaseUrl: '服务地址 baseUrl',
    customModel: '模型名称',
    customProtocol: '协议',
    customProtocolOpenai: 'OpenAI 兼容',
    customProtocolAnthropic: 'Anthropic Messages',
    customNote: '自定义服务会直接收到你发送的图片，请使用你信任的服务。',
    applyButton: '保存并测试',
    applyButtonBusy: '保存中…',
    applyButtonPreparing: '正在准备本地运行时（首次约需几分钟）…',
    backendStarting: '本地服务正在启动，请稍候…',
    backendFailed: '本地服务启动失败，请重启 FISHCODE 后重试。',
    pluginUnavailable: '视觉服务不可用：视觉插件未能加载，请重启 FISHCODE。',
    invalidKey: 'API Key 格式无效（只能包含常规字符，长度 1–512）。',
    invalidForm: '请填写完整：服务地址、模型名称不能为空。',
    privacyLine: '图片会发送给你选择的服务商用于识别；FISHCODE 不中转、不存储。',
    serviceNote: '服务可达，但未提供 /models 列表，不影响识别使用。',
    usage: {
      title: '配置成功！视觉服务已就绪',
      steps: [
        '把图片直接粘贴（Ctrl+V）或拖进聊天输入框 —— 不要点附件（回形针）按钮。',
        '输入你的问题。',
        '发送消息，然后在对话中发送 /vision-tools。',
      ],
    },
    /** Prefill-only defaults for the custom form (renderer cannot import shared). */
    customDefaults: {
      baseUrl: 'https://api.inferera.com/v1',
      model: 'gemini-3.6-flash',
      protocol: 'openai',
    },
    results: {
      'backend-not-ready': { title: '本地服务未就绪', message: '请等待本地服务启动完成后再试。' },
      busy: { title: '正在保存', message: '上一次保存尚未完成，请稍候。' },
      'credential-write-failed': { title: '无法保存密钥', message: '写入凭据文件失败，请检查磁盘权限后重试。' },
      'credential-file-unsafe': {
        title: '无法保存密钥',
        message: '凭据文件结构复杂，FISHCODE 无法安全修改；请手动在 ~/.dsh/.credentials.yaml 中添加 VISION_API_KEY。',
      },
      'settings-unavailable': { title: '无法读取设置', message: '本地视觉服务未响应，请重启 FISHCODE 后重试。' },
      'settings-conflict': { title: '设置冲突', message: '设置在其他地方被修改，请重新点击保存。' },
      'settings-rejected': { title: '设置被拒绝', message: '本地服务拒绝了配置：{detail}' },
      'origin-rejected': { title: '请求被拒绝', message: '本地服务拒绝了设置请求，请重启 FISHCODE 后重试。' },
      'health-failed': { title: '运行时未就绪', message: '视觉运行时还在准备中，请稍后重新点击保存并测试。' },
      'credential-missing': {
        title: '密钥未生效',
        message: '密钥已写入，但本地服务尚未读取到，请重新点击保存并测试。',
      },
      'key-rejected': {
        title: '密钥被拒绝',
        message: '服务商拒绝了该密钥（HTTP {detail}）。请确认密钥有效且属于所选服务商。',
      },
      'service-unreachable': {
        title: '无法连接服务',
        message: '无法连接到服务地址，请检查网络或 baseUrl 是否正确。',
      },
      'service-error': { title: '连接测试失败', message: '服务连接测试失败（{detail}）。' },
      'checks-failed': {
        title: '环境检查未通过',
        message: '视觉运行时环境异常，请重启 FISHCODE 或查看日志。',
      },
      timeout: {
        title: '操作超时',
        message: '本地服务响应超时，请重试；首次初始化可能需要几分钟。',
      },
      network: { title: '本地服务不可达', message: '无法连接本地服务，请重启 FISHCODE 后重试。' },
      'invalid-request': { title: '输入无效', message: '请检查填写的内容后重试。' },
    },
  },
} as const
