(function () {
  'use strict'

  var body = document.body
  var sprite = document.getElementById('sprite')
  var bubble = document.getElementById('bubble')

  // Generated by scripts/prepare-pet-assets.mjs (see assets/pet/frames.js).
  var FRAMES = window.__PET_FRAMES
  var ASSET_DIR = '../../assets/pet/'

  var dragging = false
  var startX = 0
  var startY = 0
  var lastX = 0
  var lastY = 0
  var lastHover = false
  var sayTimer = null
  var frameTimer = null
  var frameIndex = 0

  // Sizing is manifest-driven: frameSize is the LOGICAL sprite height in CSS
  // px (the PNGs ship at frameSize * renderScale for hi-dpi); the width follows
  // the frame aspect ratio. Set it up before the first state render.
  var frameSize = FRAMES.frameSize || 128
  sprite.style.height = frameSize + 'px'
  sprite.style.width = 'auto'
  bubble.style.bottom = frameSize + 12 + 'px'

  // Prefer an explicit manifest state; walk-left / walk-right fall back to the
  // shared 'walk' frames (the direction is then handled by the CSS mirror);
  // anything without art falls back to idle (the main process only schedules
  // states that exist, but be safe).
  function stateGroup(state) {
    if (FRAMES.states[state]) return state
    if (state === 'walk-left' || state === 'walk-right') return 'walk'
    return 'idle'
  }

  // A state may ship several animations ("variants" — e.g. a handful of idle
  // dances); pick one at random every time the state starts.
  function pickVariant(state) {
    var def = FRAMES.states[stateGroup(state)]
    if (!def) return null
    if (def.variants) return def.variants[Math.floor(Math.random() * def.variants.length)]
    return def
  }

  function renderFrame(variant) {
    if (variant) sprite.src = ASSET_DIR + variant.frames[frameIndex % variant.frames.length]
  }

  function setState(state) {
    // Body classes drive #zzz (sleep) and the .walk-left mirror. Mirroring is
    // a manifest choice: artists may ship explicit left-facing frames
    // (mirrorWalkLeft: false) instead of relying on the CSS flip.
    body.className = state + (FRAMES.mirrorWalkLeft !== false ? ' mirror' : '')
    frameIndex = 0
    var variant = pickVariant(state)
    renderFrame(variant)

    // Floor at 33ms (30 fps): enough for the GIF-derived 16.67 fps to play at
    // full speed — a 100ms floor silently capped every animation at 10 fps.
    var interval = variant ? Math.max(33, Math.round(1000 / variant.fps)) : 500
    clearInterval(frameTimer)
    frameTimer = setInterval(function () {
      frameIndex += 1
      renderFrame(variant)
    }, interval)
  }

  function isOverSprite(x, y) {
    var r = sprite.getBoundingClientRect()
    return x >= r.left && x <= r.right && y >= r.top && y <= r.bottom
  }

  document.addEventListener('mousemove', function (e) {
    // Click-through: only grab mouse events while the cursor is over the sprite.
    var over = isOverSprite(e.clientX, e.clientY)
    if (over !== lastHover) {
      lastHover = over
      window.petAPI.hover(over)
    }

    if (dragging) {
      var dx = e.screenX - lastX
      var dy = e.screenY - lastY
      lastX = e.screenX
      lastY = e.screenY
      window.petAPI.dragBy(dx, dy)
    }
  })

  sprite.addEventListener('mousedown', function (e) {
    dragging = true
    startX = e.screenX
    startY = e.screenY
    lastX = e.screenX
    lastY = e.screenY
    e.preventDefault()
  })

  document.addEventListener('mouseup', function (e) {
    if (!dragging) return
    dragging = false
    var dist = Math.hypot(e.screenX - startX, e.screenY - startY)
    if (dist < 5) window.petAPI.summon()
    else window.petAPI.drop()
  })

  sprite.addEventListener('contextmenu', function (e) {
    e.preventDefault()
    window.petAPI.menu()
  })

  window.petAPI.onState(setState)

  window.petAPI.onSay(function (text) {
    bubble.textContent = text
    bubble.hidden = false
    clearTimeout(sayTimer)
    sayTimer = setTimeout(function () {
      bubble.hidden = true
    }, 4000)
  })

  setState('idle')
})()
